[package]
name = "fractal_visualizer_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.66", features = ["nightly"]  }
syn = { version = "2.0.29", features = ["full"] } # todo: is full needed?
quote = "1.0.33"
naga_oil = "0.9.0"