[package]
name = "fractal-studio-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.93", features = ["nightly"]  }
syn = { version = "2.0.98" }
quote = "1.0.38"
naga_oil = "0.17.0"
